### ISSUE TITLE
can update a new version?

### ISSUE THREAD

**Issue by fslove** [FluffierThanThou/AnimalTab#11]
![33332](https://cloud.githubusercontent.com/assets/10248063/21789073/45cb9e88-d70d-11e6-91a0-dab31b5c7393.png)
![33331](https://cloud.githubusercontent.com/assets/10248063/21789074/45fdc016-d70d-11e6-877c-7ed0d51cecbe.png)
Show Check box? 
thanks 👍

**Comment by FluffierThanThou** [comment]
frankly, I don't want to :P I think it looks cluttered with too many boxes on the screen, and I feel like the mouseover effect + tooltip is enough to show that there is an interaction to be made there.
