### ISSUE TITLE
Filtered animal list does not autorefresh in multiple colony on A16

### ISSUE THREAD

**Issue by b606** [FluffierThanThou/AnimalTab#16]
The filtered animal list does not automatically refresh when I have multiple colonies in the same game:
- At the first load, first colony map, everything works as expected.
- Then switch to the second map and reopen the filter dialog: the animal list in the main tab stops responding to "filter by race" or "by attributes". In order to get the result, one needs to close and reopen the animals tab.

Attached: rimworld.log + a savegame.
[rimworld_log_AnimalTab.zip](https://github.com/FluffierThanThou/AnimalTab/files/769531/rimworld_log_AnimalTab.zip)

------
system:
OpenSuse 13.2
RimWorldLinux.x86_64 from steam

**Comment by FluffierThanThou** [comment]
should be fixed in the A17 prerelease (as part of a general rewrite, we now use the vanilla AnimalTab for basic functionality like finding pawns.)
