### ISSUE TITLE
Suggestion: Is it possible to get rid of the filter dialog?

### ISSUE THREAD

**Issue by b606** [FluffierThanThou/AnimalTab#17]
I really like this mod but the filter dialog hides a large portion of the screen, so I have to open and close it frequently. 
Is it possible to get rid of this filter dialog and locate the "filter by attributes" (in iconic form) at the top of the tab? The "filter by race" may be a dropdown menu or if the UI supports it, a sort of folder view by race.

**Comment by FluffierThanThou** [comment]
Thats a damn good idea, I'm going to try it out for my A17 rewrite

**Comment by FluffierThanThou** [comment]
it's now implemented. I'd love to hear your feedback on the prerelease version (only on github for now).

**Comment by Thorbane** [comment]
Is there a way to sort by species, and if so, how does it work?

**Comment by FluffierThanThou** [comment]
Not at the moment. I still have to implement the species filter, after that is done the basic filter functionality is ready. 

To be honest, I had rather overlooked the fact that people might want to sort by the filters. I'll have a look at how that should work. Many of the filters have an overlap with a specific column, so either don't need specific sorting - or I could co-opt the column sorting. That is not the case for species though, so I'll have to figure out a decent way of doing that sort and integrating it nicely into the UI.

**Comment by FluffierThanThou** [comment]
I've opened #23 to track this.
