### ISSUE TITLE
suggestion: bonds and where to click

### ISSUE THREAD

**Issue by gendalv** [FluffierThanThou/AnimalTab#18]
- Add an indication that an animal has a proper bond developed with some of your pawns (as the pawn will be sad if it dies). 
- Add some visual borders to the clickable checkmars or just have it like vanila - grayed out checkmarks, it's hard to see where I'm supposed to click.

also I'm not into the grey color of checkmarks for full trained :P

**Comment by FluffierThanThou** [comment]
I've added a vague background to check boxes, that will be more visible if the animal row is hovered over. Hopefully, that will make it easier to see where to click. I don't really want to draw 'off' check boxes, as I think they're just screen clutter. I may draw a more noticeable border though, basically mimicking the work tab.

I've also drawn the checkbox background color red for the slaughter checkbox if that animal has a proper bond.
