### ISSUE TITLE
Possible broken integration after last update

### ISSUE THREAD

**Issue by voult2** [FluffierThanThou/AnimalTab#19]
I have a mod called BetterPawnControl which successfully integrated with your mod. 
After your last update it seems two issues were introduced:
1. https://dl.dropboxusercontent.com/u/1336839/2017-02-15_23-23-59.gif
2. http://i.imgur.com/XUAdoqD.jpg

**Issue 1**
 it seems the following line of code is breaking the integration
` _instance = (MainTabWindow_Animals)DefDatabase<MainTabDef>.GetNamed( "Animals" )?.Window;`

I think it's the cast that is not working. 
`DefDatabase<MainTabDef>.GetNamed( "Animals" )?.Window; `should returns My Class.
The cast is being done to your class, sooo..,. cabummm. 

Any ideas on how to solve this? 

**Issue 2**
It seems the next code line is returning null. Not sure why, 
`texture = ContentFinder<Texture2D>.Get($"UI/Training/{trainable.defName}", false);`

**Comment by FluffierThanThou** [comment]
I'm working on a new version for A17 at the moment. Are you still keeping better pawn control up to date? If so, get in touch with me on the modding discord or the forums, and we can work something out to make integration as smooth as possible.

**Comment by voult2** [comment]
Sure! I'll get in touch with you
