### ISSUE TITLE
Work Priority tab work giver description has issues with demangling

### ISSUE THREAD

**Issue by ForsakenShell** [FluffierThanThou/AnimalTab#2]
The priority override uses the verb for the label which works fine, but when demangling the defname for the mouse-hover description it sometimes fails.

Sample output and xml which causes it attached as a zip.
[Bad_Demangle.zip](https://github.com/Karel-Kroeze/RW_EnhancedTabs/files/141297/Bad_Demangle.zip)

**Comment by Karel-Kroeze** [comment]
Fixed in ea24f7dd76d8201a7682b22b0b07525d3b523645 (hopefully)
