### ISSUE TITLE
argument out of range

### ISSUE THREAD

**Issue by Commissar0617** [FluffierThanThou/AnimalTab#32]
I know its a fluffy mod, and I suspect it's animal tab, because it does reference "trainable"
https://gist.github.com/bb7d3dbc6f875bf08b5c4f9d3e8e4301

**Comment by FluffierThanThou** [comment]
Half correct, it is a mod, but it's not animal tab. You added a mod that adds a trainable animal skill (e.g. haul, rescue, etc.) in an existing save game. The game doesn't like that.
