### ISSUE TITLE
Animal Master Enhancement

### ISSUE THREAD

**Issue by TheRealElysium** [FluffierThanThou/AnimalTab#4]
I have a suggestion for an addition to the animals tab.  Just a quality of life enhancement that would allow you to set all animals to their bonded master with a couple clicks.  It would also be nice if you could do the reverse, set all animals to have no master for the times when you are about to go in to battle and don't want unnecessary risk for your animals.  You could also take this one step further and have a button that would allow you to set all animals to a specific master, none, or bonded.  In case of no bond or bonded master skill too low, remain unchanged.

The latter bit of the suggestion may be more work than it is worth, but setting all to bonded or none would be really useful.

**Comment by FluffierThanThou** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=745157413

**Comment by TheRealElysium** [comment]
Yeah this looks like a more elegant solution, wish I had thought of it.   I was thinking within the restraints of the vanilla mechanics I suppose.  Plans to integrate this functionality?

**Comment by FluffierThanThou** [comment]
I left it here as a note to self, thinking it was related. It's not really, but yeah, I'm looking into it. As for the master assignment stuff, I just finished that, making release and such now.

**Comment by FluffierThanThou** [comment]
implemented with 8a13d11133ac3f198ef0bc7b7b16b3a6e3e696f3
