### ISSUE TITLE
Reproductive filter no longer filters out neutered animals.

### ISSUE THREAD

**Issue by Thorbane** [FluffierThanThou/AnimalTab#42]
It produces the log message saying "AnimalTab :: BirdsAndBees detected, adding fertility capacityDef to fertility filter." but still displays neutered animals as reproductive.

**Comment by FluffierThanThou** [comment]
Thanks for pointing it out! It appears that at some point vanilla added a 'minForCapable' field to capacities, which I didn't realise. 

Should be fixed now (fix was in BirdsAndBees).

**Comment by Thorbane** [comment]
It's back again Fluffy, sans the log message.  Tested with only harmony, Mod manager, The Birds and the Bees, and Animal Tab.
