### ISSUE TITLE
better pawn control pushes my icons around?

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/AnimalTab#54]
Reported by: krzarb
Description:
This could possibly be why @capitalism can't see the filter either. Better pawn control adds some extra buttons on the top left, which might push your filter icon down to where it's not visible and able to be interacted with. I can definitely confirm that when I disable better pawn control, the filter is visible to me again

**Comment by voult2** [comment]
With BPC v2.2, BPC inserts its buttons via Patches instead of inheriting from MainTabs. This means it should no longer conflict with AnimalTab (huray ^^).  However, this change only applies for game version 1.3 onwards.

**Comment by Karel-Kroeze** [comment]
thanks for that :) Closing this for now.
