### ISSUE TITLE
Medical Tab with Animal Tab bugs

### ISSUE THREAD

**Issue by zaki-29871** [FluffierThanThou/AnimalTab#58]
There functions of both **mass assign medical care (shift + left click)** and **Set default medical care (ctrl + left click)** in "medical care" of animal tab dialog are unfunctional. The status of medical treatments for each pawns in medical tab dialog (Medical Tab mod) also become default setting after using both funtions in animal tab. 

Game version is 1.2

**Comment by Karel-Kroeze** [comment]
fixed with https://github.com/fluffy-mods/MedicalTab/releases/tag/v4.4.110
