### ISSUE TITLE
Auto Slaughter not working correctly for Guinea Pigs

### ISSUE THREAD

**Issue by CathAmp** [FluffierThanThou/AnimalTab#65]
**Describe the bug**  
When I set auto slaughter to keep 6 Female Guinea Pigs, game still kills all female Guinea Pigs. I also have auto slaughter set for Yaks, Turtles and other animals with no problems there. Just FEMALE Guinea Pigs.

**Expected behavior**  
I expected 6 Female Guinea Pigs not to be killed when I set it to keep 6 Female Guinea Pigs.

**Steps to reproduce**  
Nothing really, just play

**Other mods**  
Yes. List Below from exported RimPy file. All 100% up to date.
 <activeMods>
        <li>brrainz.harmony</li>
        <li>ludeon.rimworld</li>
        <li>unlimitedhugs.hugslib</li>
        <li>oskarpotocki.vanillafactionsexpanded.core</li>
        <li>jaxe.rimhud</li>
        <li>rimfridge.kv.rw</li>
        <li>brrainz.cameraplus</li>
        <li>derekbickley.ltocolonygroupsfinal</li>
        <li>unlimitedhugs.allowtool</li>
        <li>mehni.numbers</li>
        <li>telardo.numberstraitaddon</li>
        <li>dubwise.dubsmintminimap</li>
        <li>brrainz.achtung</li>
        <li>legodude17.bba</li>
        <li>fyarn.fixablemooddebuffsalert</li>
        <li>uuugggg.replacestuff</li>
        <li>ancientgammoner.groundtargeter</li>
        <li>holdthegrenades.1trickponyta</li>
        <li>timmyliang.tradehelper</li>
        <li>divinorium.taintedrenaming</li>
        <li>captainmuscles.dropinventory</li>
        <li>hatti.qualitybuilder</li>
        <li>dubwise.dubsmintmenus</li>
        <li>tiagocc0.colorblindminerals</li>
        <li>kota.inventorytab</li>
        <li>tikubonn.dontblockdoor</li>
        <li>krafs.levelup</li>
        <li>com.github.alandariva.moreplanning</li>
        <li>fluffy.animaltab</li>
        <li>bodlosh.weaponstats</li>
        <li>vanillaexpanded.vfepower</li>
        <li>frozensnowfox.complexjobslegacy</li>
        <li>tradingspot.kv.rw</li>
        <li>murmur.walllight</li>
        <li>knight.useyourgun</li>
        <li>hobtook.mortaraccuracy</li>
        <li>longwater.smartstockpilecreation</li>
        <li>dhultgren.smarterconstruction</li>
        <li>lucifer.realisticrooms</li>
        <li>trinity.runtimegcupdated</li>
        <li>echofoxtrot.acceptablebarracks</li>
        <li>mlie.relevantstatsindescription</li>
        <li>fluffy.medicaltab</li>
        <li>fluffy.worktab</li>
        <li>edb.preparecarefully</li>
        <li>unlimitedhugs.mapreroll</li>
        <li>mlie.dismisstrader</li>
        <li>roolo.runandgun</li>
        <li>mehni.pickupandhaul</li>
        <li>uuugggg.tdpack</li>
        <li>ethereal.rejuvenate.surgery</li>
        <li>ogre.ogrestack</li>
        <li>proxyer.desurgeries.desurgeries</li>
        <li>mlie.animalharvestingspot</li>
        <li>avilmask.commonsense</li>
        <li>arandomkiwi.rimsaves</li>
        <li>void.charactereditor</li>
        <li>petetimessix.compacthediffs</li>
        <li>revolus.textilestats</li>
        <li>automatic.autolinks</li>
        <li>zylle.mapdesigner</li>
        <li>captainmuscles.gotosleep</li>
        <li>captainmuscles.chillout</li>
        <li>legodude17.qualcolor</li>
        <li>owlchemist.smartfarming</li>
        <li>falconne.bwm</li>
        <li>syrchalis.doormats</li>
        <li>mlie.prisonersdonthavekeys</li>
        <li>neitsa.preparelanding</li>
        <li>fluffy.modmanager</li>
        <li>phomor.craftingqualityrebalanced</li>
        <li>petetimessix.simplesidearms</li>
        <li>nephlite.orbitaltradecolumn</li>
        <li>murmur.subsurfaceconduit</li>
        <li>weilbyte.snapout</li>
        <li>legodude17.smartdecon</li>
        <li>uuugggg.smartmedicine</li>
        <li>dark.signs</li>
        <li>fed1splay.pawntargetfix</li>
        <li>navyseal5.moreharvestdesignators</li>
        <li>erdelf.minifyeverything</li>
        <li>falconne.heatmap</li>
        <li>cp.rimdeed</li>
        <li>spoonshortage.adogsaidanimalprosthetics</li>
        <li>falconne.aff</li>
        <li>fluffy.areaunlocker</li>
        <li>fluffy.backuppower</li>
        <li>bedrestforfoodpoisoning.1trickponyta</li>
        <li>automatic.bionicicons</li>
        <li>reiquard.caravancolonistinfo</li>
        <li>neceros.animalmedicalbed</li>
        <li>kapitanoczywisty.changemapedge</li>
        <li>navyseal5.cleaningstation</li>
        <li>juanlopez2008.lightsout</li>
        <li>uuugggg.miningpriority</li>
        <li>bustedbunny.recylethis</li>
        <li>nitrodev.absolutelynoroof</li>
        <li>mlie.temperaturegauge</li>
        <li>two.tilledsoil.120</li>
        <li>mlie.wehadatrader</li>
        <li>kikohi.whatsforsale</li>
        <li>owlchemist.toggleablereadouts</li>
        <li>ogliss.wanderjoinsplus</li>
        <li>pausbrak.rangeddps</li>
        <li>taranchuk.performanceoptimizer</li>
        <li>torann.caravanoptions</li>
        <li>aelanna.cleaningspeed</li>
        <li>fluffy.blueprints</li>
        <li>madeline.modmismatchformatter</li>
        <li>agentblac.makepawnsprisoners</li>
        <li>dubwise.dubsskylights</li>
        <li>zylle.extraalerts</li>
        <li>likeafox.haulexplicitly</li>
        <li>savestoragesettings.kv.rw</li>
        <li>mlie.stockpilestacklimit</li>
        <li>hatti.cleaningarea</li>
        <li>jaxe.pawnrules</li>
        <li>fluffy.pharmacist</li>
        <li>diddily.poweralerts</li>
        <li>showhair.kv.rw</li>
        <li>fluffy.stuffedfloors</li>
        <li>linkolas.stabilize</li>
        <li>andrewraphaellukasik.allowdeadanimals</li>
        <li>vanillaexpanded.vappe</li>
        <li>vanillaexpanded.vaeaccessories</li>
        <li>vanillaexpanded.varme</li>
        <li>vanillaexpanded.vfecore</li>
        <li>vanillaexpanded.vfearchitect</li>
        <li>vanillaexpanded.vfeart</li>
        <li>vanillaexpanded.vfefarming</li>
        <li>vanillaexpanded.vfeproduction</li>
        <li>vanillaexpanded.vfespacer</li>
        <li>zhrocks11.stackablechunks</li>
        <li>orion.hospitality</li>

**Output log**  
(https://gist.github.com/2d82ae803b2d1b2b0dc2f6df7afd9590)

**Save game**  
[Quicksave.1648981852968.zip](https://github.com/fluffy-mods/AnimalTab/files/8404391/Quicksave.1648981852968.zip)

**Screenshots**  
Screenshot will not show anything helpful

**Environment**  
 - Windows 8.1
 - 64 bits
 
**Game**
 - 64 bits
 - Epic Games
 - Version LATEST

**Comment by Karel-Kroeze** [comment]
auto slaughter is a vanilla mechanic, nothing I can do here.

**Comment by Karel-Kroeze** [comment]
thank you for the detailed report though!
